MTE 5293 - trim zoolander
rackerlabs/zoolander pull request #751
Opened 2020-01-08 19:58 UTC by runrog

I split this PR into 3 commits as it's a lot. Here's what it covers
- removes a lot of unused node modules
  - pify [promise library] (not used)
  - braces (not used)
  - clean-css (not used)
  - fs-extra (not used)
  - nan (not used)
  - request (not used)
  - semver (not used)
  - shortid (not used)
  - walk (not used)
  - concurrently (moved to dev dependency)
  - mozilla-fira-pack (moved to dev dependency)
  - node-sass (moved to dev dependency)

- automates icon documentation. It does this by automating the _harp.json global variables file. On `npm start`, a node script grabs the icons list from the fontello config, then adds that list as a global variable, then the icons page loops that and outputs all of our icons. (no more manually updating the icons page every time there's an icon update)

- removes old 0365 tables / zoolander page references.

- removes old resource center styling and old markup. no more references to "refresh", it's not just resource center.

- various documentation cleanup where page layouts were broken and links weren't valid.

2020-01-16 17:36 UTC, WidgetsBurritos requested changes

2020-01-16 17:36 UTC, WidgetsBurritos commented on dist/css/derek.css
> -html{font-family:sans-serif;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%}body{margin:0}article,aside,details,figcaption,figure,footer,header,hgroup,main,menu,nav,section,summary{display:bl
Let's not push any of the `dist` folder up.  The version patching will handle this for us.

2020-01-16 19:50 UTC, runrog commented on dist/css/derek.css
> -html{font-family:sans-serif;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%}body{margin:0}article,aside,details,figcaption,figure,footer,header,hgroup,main,menu,nav,section,summary{display:bl
done. not sure what happened there.

2020-01-22 15:50 UTC, WidgetsBurritos approved these changes
:+1: LGTM

2020-01-23 22:52 UTC, WidgetsBurritos commented
[run ci]

2020-01-24 17:19 UTC, merged