feat(tracking): new tracking for solve ctas
rackerlabs/zoolander pull request #768
Opened 2020-02-25 16:48 UTC by runrog

2020-02-25 18:26 UTC, runrog commented
[run ci]

2020-02-25 20:50 UTC, WidgetsBurritos approved these changes
👍 Approved, but as noted in ticket, we need the class added to the corresponding places in solve/www repos as well.

2020-03-04 19:41 UTC, WidgetsBurritos approved these changes
👍 LGTM

2020-03-04 21:16 UTC, WidgetsBurritos requested changes

2020-03-04 21:16 UTC, WidgetsBurritos commented on styleguide/derek/global-components/tracking/tracking.js
> +        event: 'cta.click',
Just realized, the `cta.click` event is incorrect. Can you change this event to `ga.event` instead?

2020-03-04 21:30 UTC, WidgetsBurritos approved these changes
👍 on 75ec5b1d5e2f7a3d8ea8dc2218a5c8004698ae07

2020-03-04 21:37 UTC, merged