feat(styles): new footer design
rackerlabs/zoolander pull request #783
Opened 2020-03-30 20:13 UTC by runrog

2020-03-31 21:29 UTC, WidgetsBurritos requested changes

2020-03-31 21:29 UTC, WidgetsBurritos commented on styleguide/derek/global-components/footer/_footer.scss
> +  font-weight: 500;
We only have the 500 weight installed on the rackspace_spa theme, so this change won't make any sort of difference elsewhere on the site.

2020-03-31 21:29 UTC, WidgetsBurritos commented on styleguide/derek/global-components/footer/footer.ejs
> +        </a>
For accessibility purposes, we'll need text inside the `<span>`.  You can then use CSS to hide that text, but we need it for screen readers. 

So for example: 
```<span class="fa fa-2x fa-facebook-official">Rackspace on Facebook</span>```

2020-03-31 21:29 UTC, WidgetsBurritos commented on styleguide/derek/global-components/footer/_footer.scss
> +  font-weight: 500;
We only have the 500 weight installed on the rackspace_spa theme, so this change won't make any sort of difference elsewhere on the site.

2020-04-07 17:44 UTC, runrog commented
[run ci]

2020-04-07 18:13 UTC, pobtastic commented on styleguide/derek/global-components/footer/footer.ejs
> +          <span class="footer-social-ln">Linkedin</span>
Minor: s/b "LinkedIn" (capital "I").

2020-04-07 18:13 UTC, pobtastic commented
LGTM 👍

2020-04-07 18:30 UTC, runrog commented on styleguide/derek/global-components/footer/footer.ejs
> +          <span class="footer-social-ln">Linkedin</span>
I got you!

2020-04-10 16:06 UTC, WidgetsBurritos approved these changes
👍 LGTM

2020-04-13 14:58 UTC, merged